"""Phase 4 Back End console program.

Program intention:
- Read the previous day's Master Bank Accounts file.
- Read a merged Bank Account Transaction file generated by Front End sessions.
- Apply transactions overnight to produce a new Master Bank Accounts file.
- Write the next day's Current Bank Accounts file.

Run:
    python backend_main.py <old_master_file> <merged_transaction_file> <new_master_file> <new_current_file>
"""

import sys

from batch_processor import BatchProcessor
from file_handler import FileHandler


def main() -> None:
    """Run the Back End batch processor with explicit file-path arguments."""
    if len(sys.argv) != 5:
        print(
            'Usage: python backend_main.py <old_master_file> <merged_transaction_file> '
            '<new_master_file> <new_current_file>'
        )
        sys.exit(1)

    old_master_file = sys.argv[1]
    merged_transaction_file = sys.argv[2]
    new_master_file = sys.argv[3]
    new_current_file = sys.argv[4]

    file_handler = FileHandler()

    try:
        old_master_content = file_handler.read_file(old_master_file)
        merged_transaction_content = file_handler.read_file(merged_transaction_file)
        include_plan_output = file_handler.master_accounts_include_plan(old_master_content)
        accounts = file_handler.parse_master_accounts_file(old_master_content)
        transactions = file_handler.parse_transaction_file(merged_transaction_content)
        processor = BatchProcessor(accounts)
        constraint_messages = processor.process(transactions)
        for message in constraint_messages:
            print(message)

        updated_accounts = processor.get_accounts()
        file_handler.write_file(
            file_handler.generate_master_accounts_file(updated_accounts, include_plan=include_plan_output),
            new_master_file,
        )
        file_handler.write_file(
            file_handler.generate_current_accounts_file(updated_accounts, include_plan=include_plan_output),
            new_current_file,
        )
    except Exception as exc:
        print(f'ERROR: {exc}')
        sys.exit(1)


if __name__ == '__main__':
    main()
